#!/usr/bin/with-contenv bash

exec \
	s6-setuidgid abc python3 /watcher/watcher.py \
	--address 0.0.0.0 \
  --port 9090 \
  --conf /config/config.cfg \
  --db /config/watcher.sqlite \
  --log /config/logs/ 
